Disable rdkb_extender and WAN_FAILOVER_SUPPORTED in BCI builds
rdkb_extender and WAN_FAILOVER_SUPPORTED causes BCI build errors.
| ../../../../../../../../../rdkb/components/opensource/ccsp/Utopia/source/service_routed/service_routed.c: In function 'gen_zebra_conf':
| ../../../../../../../../../rdkb/components/opensource/ccsp/Utopia/source/service_routed/service_routed.c:857:23: error: 'last_broadcasted_prefix' undeclared (first use in this function)
|   857 |             if(strlen(last_broadcasted_prefix) != 0)
|       |                       ^~~~~~~~~~~~~~~~~~~~~~~

Change-Id: Id67c7ce7919f622d461f75d8f8aeef13f8cf2a27