RDKCMF-8877: Fix wpeframework-clientlibraries 64bit build
-fpermissive is required to fix wpeframework-clientlibraries 64bit build, with multiples of
error: loses precision [-fpermissive]

Change-Id: Ic7da9f62cb29818c6c1f02641c21d09bef1ad801